scrape_configs:
    - job_name: termit
      metrics_path: '/termit/actuator/prometheus'
      scrape_interval: 5s
      basic_auth:
          username_file: "/etc/prometheus/username_file"
          password_file: "/etc/prometheus/password_file"
      static_configs:
          - targets:
                - 'termit-server:8080'
